version: '3'
services:
  be:
    container_name: be
    build: ./be
    volumes:
      - ./be/app:/app
    ports:
      - "5000:5000"
    networks:
      - mynet

  fe:
    container_name: fe
    build: ./fe
    volumes:
      - ./fe/app:/app
      - fe_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

volumes:
  fe_node_modules:
